on: [push]
name: Build and deploy container to Azure Container Apps

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: 'Checkout Fred'
        uses: actions/checkout@v4

      - name: 'Checkout database'
        uses: actions/checkout@v4
        with:
          repository: jeroenvdmeer/feyod
          path: ./feyod

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: .
          dockerfilePath: ./Dockerfile
          registryUrl: ${{ secrets.REGISTRY_URL }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          imageToBuild: ${{ secrets.IMAGE }}
          location: ${{ secrets.AZURE_LOCATION }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          containerAppEnvironment: ${{ secrets.AZURE_CONTAINER_APP_ENVIRONMENT }}
          containerAppName: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
          ingress: external
          targetPort: 8000
          disableTelemetry: true
          environmentVariables: ${{secrets.ENV_VARS}}