on: [push]
name: Build and deploy container to Azure Container Apps

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: 'Checkout Fred'
        uses: actions/checkout@v4

      - name: 'Checkout database'
        uses: actions/checkout@v4
        with:
          repository: jeroenvdmeer/feyod
          path: ./feyod

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: .
          dockerfilePath: ./Dockerfile
          registryUrl: ${{ secrets.REGISTRY_URL }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          imageToBuild: ${{ secrets.IMAGE }}
          location: ${{ secrets.AZURE_LOCATION }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          containerAppEnvironment: ${{ secrets.AZURE_CONTAINER_APP_ENVIRONMENT }}
          containerAppName: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
          ingress: external
          targetPort: 8000
          disableTelemetry: true
          environmentVariables: LOG_LEVEL="DEBUG" FEYOD_DATABASE_URL="sqlite+aiosqlite:///feyod/feyod.db" LLM_PROVIDER=${{ secrets.LLM_PROVIDER }} LLM_API_KEY=${{ secrets.LLM_API_KEY }} LLM_MODEL=${{ secrets.LLM_MODEL }} EXAMPLE_SOURCE="mongodb" EXAMPLE_DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }} EXAMPLE_DB_NAME=${{ secrets.DB_NAME }} EXAMPLE_DB_COLLECTION=${{ secrets.DB_COLLECTION }} CONTEXT_RECENT_MESSAGES_KEPT="25" CONTEXT_OLDER_MESSAGES_CHAR_THRESHOLD="3000" CHAINLIT_AUTH_SECRET=${{ secrets.CHAINLIT_AUTH_SECRET }} LITERAL_API_KEY=${{ secrets.LITERAL_API_KEY }} OAUTH_AUTH0_CLIENT_ID=${{ secrets.OAUTH_AUTH0_CLIENT_ID }} OAUTH_AUTH0_CLIENT_SECRET=${{ secrets.OAUTH_AUTH0_CLIENT_SECRET }} OAUTH_AUTH0_DOMAIN=${{ secrets.OAUTH_AUTH0_DOMAIN }}